packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  # TypeScript
  typescript: ^5.7.3
  '@types/node': ^22.10.7

  # React
  react: ^19.2.3
  react-dom: ^19.2.3
  '@types/react': ^19
  '@types/react-dom': ^19
